services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: $PSQL_PASS 
      POSTGRES_USER: $PSQL_USER
      POSTGRES_DB: $PSQL_DB
    ports:
      - "5432:5432"
    networks:
      - net-01

  # logger

  movie-watchlist:
    environment:
      PSQL_USER: $PSQL_USER
      PSQL_DB: $PSQL_DB
      PSQL_PASS: $PSQL_PASS 
      PSQL_ADDRESS_PROD: $PSQL_ADDRESS_PROD
      PSQL_ADDRESS_HML: $PSQL_ADDRESS_HML
    build: ./app/
    restart: always
    ports:
      - "9800:9800"
    networks:
      - net-01

networks:
  net-01:
    driver: bridge
