services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: lu123cas
      POSTGRES_USER: postgres
      POSTGRES_DB: movie-watchlist
    ports:
      - "5432:5432"
    networks:
      - net-01

  movie-watchlist:
    build: ./app/
    restart: always
    ports:
      - "9800:9800"
    networks:
      - net-01

networks:
  net-01:
    driver: bridge
